### ISSUE TITLE
Mismatch on suggested route in scaffolded code and root prefix for route

### ISSUE THREAD

**Issue by dmartinezg** [mulesoft/osprey-cli#36]
Apikit registers itself on '/api':

``` js
apiKit.register('/api', app, {
  ramlFile: path.join(__dirname, '/assets/raml/api.raml'),
  enableConsole: true,
  enableMocks: true
});
```

But the route overload is not on `/api`:

```
// Adding business logic to a valid RAML Resource
// apiKit.get('/examples/:exampleId', function(req, res) {
//   res.send({ name: 'example' });
// });
```

**Comment by 3miliano** [comment]
The route that you register using apiKit.get is always relative to the basePath defined in apiKit.register. 

Are you saying that is not the case? Or that you want to have /api also on apiKit.get?

**Comment by dmartinezg** [comment]
> The route that you register using apiKit.get is always relative to the basePath defined in apiKit.register.

If that is the case then we should document it

On an aside, this together with #35 leaves me not really knowing what to expect here

**Comment by jcenturion** [comment]
I already added documentation for apiKit.get in README.md (https://github.com/mulesoft/apikit-node/blob/master/README.md).

I will close this bug.
