### ISSUE TITLE
There should be a "strict" mode that turns mocking off and that warns of any routes that do not have an overriding handler

### ISSUE THREAD

**Issue by dmartinezg** [mulesoft/osprey-cli#40]

**Comment by dmartinezg** [comment]
I should also warn of any Osprey registered routes (using `api.get()` or such) that are no in the RAML file.

**Comment by 3miliano** [comment]
There is no warning for routes that are not on the RAML files, that should be a blunt error straight forward. We do not indent to allow declaring routes that are not on the RAML, at least no using Osprey. You can do so directly via express thou.

**Comment by jcenturion** [comment]
Closing.

There is an enhancement for this topic on Osprey at https://github.com/mulesoft/osprey/issues/23.
