### ISSUE TITLE
What happens if I have a resource named "/console"?

### ISSUE THREAD

**Issue by dmartinezg** [mulesoft/osprey-cli#42]

**Comment by jcenturion** [comment]
If you have a resource "/console" defined at RAML level the API Console will not be displayed.

**Comment by 3miliano** [comment]
Is the path of the console configurable? If not, we should make it so. In the case of conflict the developer can choose a different path for the console.

**Comment by jcenturion** [comment]
The console path is not configurable. I will add an issue for that.

Closing this topic.
