### ISSUE TITLE
Error when Installing APIKit Node CLI globally

### ISSUE THREAD

**Issue by nohorbee** [mulesoft/osprey-cli#54]
Following the installation steps on the readme.md, I'm getting the following errors when installing the client globally:
npm ERR! addLocal Could not install /Users/nohorbee/Projects/apikit-node-cli
npm ERR! Error: ENOENT, stat '/Users/nohorbee/Projects/apikit-node-cli'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "/Users/nohorbee/Projects/apikit-node-cli"
npm ERR! cwd /Users/nohorbee/workspaces/apikit-node-cli
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! path /Users/nohorbee/Projects/apikit-node-cli
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/nohorbee/workspaces/apikit-node-cli/npm-debug.log
npm ERR! not ok code 0

**Comment by jcenturion** [comment]
It would be great if you can attach the file npm-debug.log
