### ISSUE TITLE
Validator should reject requests with query parameters not in the RAML file

### ISSUE THREAD

**Issue by dmartinezg** [mulesoft/osprey-cli#55]
If a resource+method does not have query parameters defined or has some, apikit should reject requests made with query parameters not defined in the RAML file.

**Comment by jcenturion** [comment]
The expected behaviour will be:
- If there are not query parameters defined, Osprey will accept any sent parameter
- If there are some query parameters defined,  Osprey is going to validate that only such parameters will be present

**Comment by dmartinezg** [comment]
Can make it so that in strict mode, only strict adherence to the RAML is accepted?

**Comment by jcenturion** [comment]
Moved to Oprey repo.
